#!/usr/bin/env bash
# generate_stdlib_man.sh — extract @man blocks from stdlib headers
# Usage: ./scripts/generate_stdlib_man.sh
# Reads all *.h files under grayc/src/stdlib/ that contain @module tags.
# Generates cli/stdlib_man_data.go (committed, do not edit by hand).
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
STDLIB_DIR="$ROOT/grayc/src/stdlib"
OUT="$ROOT/cli/stdlib_man_data.go"

# Collect all @man blocks from all stdlib headers into a TSV:
#   name <TAB> module <TAB> group <TAB> sig <TAB> desc <TAB> example
TMPFILE="$(mktemp /tmp/gray_stdlib_man_XXXXXX.tsv)"
trap 'rm -f "$TMPFILE"' EXIT

for header in "$STDLIB_DIR"/*.h; do
  awk '
    /^\/\*@man / {
      name = substr($0, 8); gsub(/[[:space:]]/, "", name)
      in_block = 1; mod = ""; grp = ""; kind = "func"; sig = ""; fields = ""; desc = ""; ex = ""; in_ex = 0; next
    }
    in_block && /\*@module / { mod    = substr($0, index($0, "@module ") + 8); gsub(/^[[:space:]]+|[[:space:]]+$/, "", mod);    next }
    in_block && /\*@group /  { grp    = substr($0, index($0, "@group ")  + 7); gsub(/^[[:space:]]+|[[:space:]]+$/, "", grp);    next }
    in_block && /\*@kind /   { kind   = substr($0, index($0, "@kind ")   + 6); gsub(/^[[:space:]]+|[[:space:]]+$/, "", kind);   next }
    in_block && /\*@sig /    { sig    = substr($0, index($0, "@sig ")    + 5); gsub(/^[[:space:]]+|[[:space:]]+$/, "", sig);    next }
    in_block && /\*@field /  {
      fline = substr($0, index($0, "@field ") + 7)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", fline)
      gsub(/"/, "\\\"", fline)
      fields = (fields == "" ? fline : fields "\\n" fline)
      next
    }
    in_block && /\*@desc /   { desc = substr($0, index($0, "@desc ")  + 6); gsub(/^[[:space:]]+|[[:space:]]+$/, "", desc); next }
    in_block && /\*@example/ { in_ex = 1; next }
    in_block && /\*@end/     { in_ex = 0; next }
    in_block && in_ex {
      line = $0; sub(/^ \*   /, "", line)
      gsub(/\\/, "\\\\", line)
      gsub(/"/, "\\\"", line)
      ex = (ex == "" ? line : ex "\\n" line); next
    }
    in_block && /\*\// {
      if (mod != "") {
        gsub(/"/, "\\\"", sig); gsub(/"/, "\\\"", desc)
        printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n", name, mod, grp, kind, sig, fields, desc, ex
      }
      in_block = 0; next
    }
  ' "$header"
done > "$TMPFILE"

{
  echo "// Code generated by scripts/generate_stdlib_man.sh — do not edit."
  echo "package main"
  echo ""
  echo "// StdlibManEntry holds documentation for a single stdlib function, type, or constant."
  echo "type StdlibManEntry struct {"
  echo "	Module  string"
  echo "	Group   string"
  echo "	Kind    string // \"func\", \"type\", or \"const\""
  echo "	Sig     string // for funcs: signature string"
  echo "	Fields  string // for types: newline-separated \"name\\ttype\" pairs"
  echo "	Desc    string"
  echo "	Example string"
  echo "}"
  echo ""
  echo "// stdlibManDocs is the per-function lookup table used by gray man <name>."
  echo "var stdlibManDocs = map[string]StdlibManEntry{"
  awk -F'\t' '{
    printf "\t\"%s.%s\": {Module: \"%s\", Group: \"%s\", Kind: \"%s\", Sig: \"%s\", Fields: \"%s\", Desc: \"%s\", Example: \"%s\"},\n", $2, $1, $2, $3, $4, $5, $6, $7, $8
  }' "$TMPFILE"
  echo "}"
  echo ""

  # stdlibModules: module -> ordered flat list of names
  echo "// stdlibModules maps module names to their ordered function lists."
  echo "var stdlibModules = map[string][]string{"
  awk -F'\t' '
    {
      name = $1; mod = $2
      if (!(mod in seen_mod)) { mod_order[++mod_count] = mod; seen_mod[mod] = 1 }
      entries[mod] = (entries[mod] == "" ? "\"" name "\"" : entries[mod] ", \"" name "\"")
    }
    END {
      for (i = 1; i <= mod_count; i++) {
        m = mod_order[i]
        printf "\t\"%s\": {%s},\n", m, entries[m]
      }
    }
  ' "$TMPFILE"
  # Note: $1=name $2=mod $3=grp $4=kind $5=sig $6=fields $7=desc $8=ex
  echo "}"
  echo ""

  # stdlibModuleGroups: module -> ordered groups, each group is label + names
  # Format: []stdlibGroup{{Label, []string{...}}, ...}
  echo "// stdlibGroup is one labeled group of names within a module index."
  echo "type stdlibGroup struct {"
  echo "	Label string"
  echo "	Names []string"
  echo "}"
  echo ""
  echo "// stdlibModuleGroups maps module names to their display groups."
  echo "var stdlibModuleGroups = map[string][]stdlibGroup{"
  awk -F'\t' '
    {
      name = $1; mod = $2; grp = ($3 != "" ? $3 : "Other")
      # $4=kind $5=sig $6=fields $7=desc $8=ex
      mg_key = mod "|" grp
      if (!(mg_key in seen_grp)) {
        gc = ++grp_count[mod]
        grp_label[mod "_" gc] = grp
        seen_grp[mg_key] = 1
      }
      grp_entries[mg_key] = (grp_entries[mg_key] == "" ? "\"" name "\"" : grp_entries[mg_key] ", \"" name "\"")
      if (!(mod in seen_m)) { mod_order[++mod_c] = mod; seen_m[mod] = 1 }
    }
    END {
      for (i = 1; i <= mod_c; i++) {
        m = mod_order[i]
        printf "\t\"%s\": {\n", m
        for (j = 1; j <= grp_count[m]; j++) {
          g = grp_label[m "_" j]
          printf "\t\t{Label: \"%-14s\", Names: []string{%s}},\n", g, grp_entries[m "|" g]
        }
        printf "\t},\n"
      }
    }
  ' "$TMPFILE"
  echo "}"
} > "$OUT"

echo "generate_stdlib_man.sh: wrote $OUT"
